### ISSUE TITLE
Ruby Conventions

### ISSUE THREAD

**Issue by PatrickTulskie** [sam09/ImageScraper#1]
A few things I noticed when going through the gem:
1. Ruby uses 2 spaces for indenting and this looks to be using 4.
2. Method names are `camelCase` but in Ruby they should be `snake_case`
3. File names are like `ImageScraper.rb` but they should be `image_scraper.rb`
4. There isn't any documentation in the readme about how exactly to use the gem

Just some suggestions on how to make this a better gem.  Hope this helps!

**Comment by sam09** [comment]
Thanks a lot

**Comment by sam09** [comment]
I think now its fine.

**Comment by PatrickTulskie** [comment]
I haven't tested it but it looks like this also needs to be fixed: https://github.com/sam09/ImageScraper/blob/master/lib/image_scraper.rb#L32
